### ISSUE TITLE
Change order of abbreviation and full word(s)

### ISSUE THREAD

**Issue by dscso** [ENIB-Community/glossarium#11]
It is more readable to make the introduction of a word the other way around:
Transmission Control Protocol (TCP) instead of TCP (Transmission Control Protocol) how it is now.

The first mentioned is the introduction style commonly used in papers etc.

**Comment by JuliDi** [comment]
I agree, that seems to be more common. Probably best to add a switch for that so both methods are available.

**Comment by slashformotion** [comment]
for release 0.3.0 i will keep is this way until proper support for plurals is merged
