### ISSUE TITLE
Add a glossary file format.

### ISSUE THREAD

**Issue by PJungkamp** [ENIB-Community/glossarium#15]
I wanted to manage my glossary using a YAML file (similar to `hayagriva` used by the typst `bibliography`). I've written up a simple prototype, would you be open to adding it?

See https://typst.app/docs/reference/model/bibliography/

Regards,
Philipp Jungkamp

---

The `glossary` command here is modeled after the `bibliography` command and accepts similar arguments.

- I renamed `show-all` of `print-glossary` to `full` to match `bibliography`.
- I renamed the `desc` field to `description`, but this is just my preference and your choice to make.
- I added the automatic insertion of a `Glossary` section title. I'd like to be able to have e.g. the `#glossary("glossary.yaml")` right next next to `#bibliography("bibliography.yaml")`.
- I added a fair amount of input validation with nice error messages.

---

<details><summary>The glossary file format.</summary>

```yaml
# glossary.yaml

ntc:
  short: NTC
  long: Nonlinear Transform Coding
  description: |
    This is the opposite of @ltc.

ltc:
  short: LTC
  long: Linear Transform Coding
  description: |
    Transform Coding constraint to linear transforms.
```

</details>

<details><summary>The function prototype.</summary>

```typst
#import "@preview/glossarium:0.2.5": make-glossary, print-glossary

#let glossary(files, title: "Glossary", full: false) = {
  let read-glossary-entries(file) = {
    let entries = yaml(file)

    assert(
      type(entries) == dictionary,
      message: "The glossary at `" + file + "` is not a dictionary",
    )

    for (k, v) in entries.pairs() {
      assert(
        type(v) == dictionary,
        message: "The glossary entry `" + k + "` in `" + file + "` is not a dictionary",
      )

      for key in v.keys() {
        assert(
          key in ("short", "long", "description"),
          message: "Found unexpected key `" + key + "` in glossary entry `" + k + "` in `" + file + "`",
        )
      }

      assert(
        type(v.short) == str,
        message: "The short form of glossary entry `" + k + "` in `" + file + "` is not a string",
      )

      if "long" in v {
        assert(
          type(v.long) == str,
          message: "The long form of glossary entry `" + k + "` in `" + file + "` is not a string",
        )
      }

      if "description" in v {
        assert(
          type(v.description) == str,
          message: "The description of glossary entry `" + k + "` in `" + file + "` is not a string",
        )
      }
    }

    return entries.pairs().map(((key, entry)) => (
      key: key,
      short: eval(entry.short, mode: "markup"),
      long: eval(entry.at("long", default: ""), mode: "markup"),
      desc: eval(entry.at("description", default: ""), mode: "markup"),
      file: file,
    ))
  }

  let entries = ()

  if type(files) != array {
    files = (files,)
  }

  for file in files {
    let new = read-glossary-entries(file)

    for entry in new {
      let duplicate = entries.find((e) => e.key == entry.key)
      if duplicate != none {
        panic("Found duplicate key `" + entry.key + "` in files `" + entry.file + "` and `" + duplicate.file + "`")
      }
    }

    entries += new
  }

  [= #title]
  print-glossary(entries, show-all: full)
}

#set page(numbering: "1")
#show: make-glossary

= Test Document

Reference to @ntc

#glossary("glossary.yaml")
```

![test](https://github.com/ENIB-Community/glossarium/assets/56401138/34438c66-7501-4850-bd5c-6bc7c981d308)

</details>

**Comment by slashformotion** [comment]
i am not really sure this is within the scope of glossarium. what i do personally is that i have a typst file that declares the array of glossary entry and then i import that array into my main document. 
I don't really see why using a yml file would be better than a Typst file.

**Comment by slashformotion** [comment]
I am open to the idea but it's a big change and there is some other things i want to do before like handlings plurals

**Comment by PJungkamp** [comment]
Thank you for your response!

So let's wait for typst and the glossarium package to cook and see whether other people chime in.

**Comment by slashformotion** [comment]
I've spent some time thinking about this potential API change. For me, the problem is that the yaml file will always be less "expressive" than a typst file. For example, in a YAML file, typst-lsp or the web app won't be able to locate exactly where the errors come from if the "desc" field becomes long and includes a lot of complex typst markup. 


I think the best thing to do is to provide a utility function in a sub-module that will do the job of reading a yml, json or other file and returning the list of expected dictionaries.

If one day glossaries become a native feature of the typst compiler, then yes, a glossary file might make more sense. In this case I don't think it's really appropriate. 


Sorry to have to give a negative answer to this proposal.
