### ISSUE TITLE
Can't compile with Typst 0.11.0

### ISSUE THREAD

**Issue by St0wy** [ENIB-Community/glossarium#31]
When importing the project with 

```typst
#import "@preview/glossarium:0.3.0": make-glossary, print-glossary, gls, glspl 
#show: make-glossary
```

and then try to reference an entry of my glossary, it fails with this error message : 
```
error: expected string or function, found none
    ┌─ @preview/glossarium:0.3.0\glossarium.typ:138:59
    │
138 │                       ).values.map(x => link(x)[#numbering(x.page-numbering(), ..counter(page).at(x))]).join(", ")
    │                                                            ^^^^^^^^^^^^^^^^^^

```

Here is a minimal reproducible example : https://typst.app/project/ritymIxMWf2FvbHLJb6gcJ

Edit: As a workaround, back references can be disabled with `disable-back-references: true`. It doesn't fail once this is set to true.

**Comment by slashformotion** [comment]
it is somewhat of a know issue. In my humble opinion, it make no sense that the page-numbering is not setup by default by typst if not provided.
