### ISSUE TITLE
glossarium breaks if page numbering is not set

### ISSUE THREAD

**Issue by JuliDi** [ENIB-Community/glossarium#4]
The package's example works because it does `#set page(numbering: "1", paper: "a5")`.
However, if you don't have page numbering set, e.g., because you print it manually in a custom footer, it will break in this line https://github.com/typst/packages/blob/4b8adb3f36a4d20d01e505230f481ebce6259c01/packages/preview/glossarium/0.2.2/glossarium.typ#L141

Unfortunately I am rather new to typst and don't yet have an idea how to fix it except for globally setting the page numbering as in the example.

**Comment by slashformotion** [comment]
i think that you can set the page numbering and use a custom footer, but perhaps i am mistaken. Unfortunatly i glossarium need the page numbering to be able to retreive the number of the page a glossary entry appeared and display it with the correct numbering pattern

**Comment by JuliDi** [comment]
Yes that should work and that's how I've worked around it. Probably something that would need to be fixed on Typst's side.
