### ISSUE TITLE
Plurals not working with reference syntax

### ISSUE THREAD

**Issue by GGP305** [ENIB-Community/glossarium#43]
As you can see in the images provided below, the syntax specified in the examples `@key:pl` is not working correctly and gives a `Label does not exists in the document` error.

![image](https://github.com/ENIB-Community/glossarium/assets/121891306/9fad2f4c-00b2-41b4-8dbf-1061b2d55baa)

![image](https://github.com/ENIB-Community/glossarium/assets/121891306/e56f31c8-e84a-4942-a1d2-9fa60477af36)

**Comment by slashformotion** [comment]
I am closing this, i made multiples attempts at reproducing the issue and i can't. If you can provide the information i mentioned previously, please do not hesitate to post it a reopen this issue
